### ISSUE TITLE
Create and update file howToMakeAPr.md

### ISSUE THREAD

**Issue by kindacoder** [kindacoder/Learn-how-to-make-a-pr#10]
**What to update :**
---
Write a beautiful tutorial for absolute beginners on **how to make a pull request ?** in a very simple language.
:heavy_check_mark: Make sure you use Emoji's for tutorial :+1: 
:point_right: Please create a new file named **howToMakeAPr.md** and write the tutorial.

**Comment by lifeLessCoder** [comment]
@kindacoder Can I start working on this issue?

**Comment by kindacoder** [comment]
yes @lifeLessCoder You should :+1:

**Comment by lifeLessCoder** [comment]
#34 Done @kindacoder

**Comment by kindacoder** [comment]
> #34 Done @kindacoder

It's awesome bro :+1: . You have written a kickass tutorial .

**Comment by lifeLessCoder** [comment]
@kindacoder Thank you!
