### ISSUE TITLE
Add your profile : Make your first pull request

### ISSUE THREAD

**Issue by kindacoder** [kindacoder/Learn-how-to-make-a-pr#23]
Add your profile and Create your first pull request. Follow all the guidelines

- [ ] I have Added my profile as **`students list/firstName_lastName_githubId.md`** 

- [ ] I have Starred this repository.

**Comment by rbo13** [comment]
Will do this one :)

**Comment by kindacoder** [comment]
> Will do this one :)

Ok. Do and submit a pull request :+1:

**Comment by rbo13** [comment]
Added my PR @kindacoder 👍

**Comment by Soumya44** [comment]
I am in

**Comment by kindacoder** [comment]
> I am in

Have you followed all the guidelines ?

**Comment by Soumya44** [comment]
> > I am in
> 
> Have you followed all the guidelines ?

Yes

**Comment by kindacoder** [comment]
> > I am in
> 
> Have you followed all the guidelines ?

ok @Soumya44 have you starred the repository ?

**Comment by Soumya44** [comment]
> > > I am in
> > 
> > 
> > Have you followed all the guidelines ?
> 
> ok @Soumya44 have you starred the repository ?

Starred Now. :-)

**Comment by kindacoder** [comment]
> > > > I am in
> > > 
> > > 
> > > Have you followed all the guidelines ?
> > 
> > 
> > ok @Soumya44 have you starred the repository ?
> 
> Starred Now. :-)

@Soumya44  can you please see the template and match it with your .md file ?

**Comment by Rohit-Kmr** [comment]
stared and pull request sent

**Comment by afrzhussain** [comment]
added my Profile  #33 .@kindacoder please merge with PR after checking.
